# Generated by Django 5.1 on 2025-09-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_shoppingcart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
