# Generated by Django 5.1 on 2025-10-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_privacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Privacy',
        ),
    ]
