# Generated by Django 5.1 on 2025-10-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.project')),
            ],
        ),
    ]
