# Generated by Django 5.1 on 2025-10-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
