# Generated by Django 5.1 on 2025-11-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_messages_user_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
