# Generated by Django 5.1 on 2025-11-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
