# Generated by Django 5.1 on 2025-11-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_description', to='product.project')),
                ('project_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_image', to='product.project')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='product.project')),
            ],
        ),
    ]
