# Generated by Django 5.1 on 2025-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_projectsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='project_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
